In [1]:
import numpy as np

In [2]:
#Creating numpy array

In [3]:
my_list = [1,2,3]

In [6]:
x = np.array(my_list)

In [7]:
type(x)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(2,3)

array([[0.21900785, 0.2946819 , 0.64973653],
       [0.10497014, 0.0970799 , 0.31351059]])

In [23]:
np.random.randn(2,3)

array([[-0.85189808, -0.73021032,  0.16048349],
       [-1.03082867,  2.22477007, -0.13913839]])

In [26]:
np.random.randint(1,100)

42

In [37]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [38]:
ranarr

array([11, 15, 46, 18, 20, 15, 47, 37, 39, 15])

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [46]:
arr.reshape(25,1).shape

(25, 1)

In [48]:
arr.dtype #data type of array data

dtype('int64')

In [49]:
ranarr

array([11, 15, 46, 18, 20, 15, 47, 37, 39, 15])

In [52]:
ranarr.argmax() #returns index location of highest value

6

In [53]:
ranarr.argmin()

0