In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr[8]

8

In [7]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
slice = arr[0:6]

In [9]:
slice

array([100, 100, 100, 100, 100,   5])

In [10]:
slice[:] = 99

In [11]:
slice

array([99, 99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy = arr.copy()

In [14]:
arr_copy[:] = 200

In [15]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [18]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
mat[0]

array([ 5, 10, 15])

In [20]:
mat[2]

array([35, 40, 45])

In [21]:
mat[1][1]

25

In [22]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
mat[0][2] #find 15

15

In [24]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
mat[1:, :2]

array([[20, 25],
       [35, 40]])

In [32]:
# CONDITIONAL SELECTION

In [34]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 4

In [37]:
arr[bool_arr] #only returns true values from original array

array([ 5,  6,  7,  8,  9, 10])

In [38]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [39]:
arr[arr<4]

array([1, 2, 3])